version: '2.4'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mysql?&createDatabaseIfNotExists=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    -  logap_api:/var/lib/mysql
    mem_limit: 512m

  logap-api:
    image: registry.hub.docker.com/matheusaquatico/logap-api:1.0-SNAPSHOT
    ports:
    - "8081:8080"
    environment:
      <<: *database-variables
    mem_limit: 512m

volumes:
  logap_api: