version: '2.4'
x-database-variables: &database-variables
  SPRING_DATASOURCE_URL: jdbc:mysql://mysqlCompras:3307/mysql?&createDatabaseIfNotExists=true
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root

services:
  db:
    image: mysql
    container_name: mysqlCompras
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
    ports:
    - "3307:3307"
    volumes:
    -  crudLoja_api:/var/lib/mysql
    mem_limit: 512m

#  crudLoja-api:
#    image: registry.hub.docker.com/matheusaquatico/crudloja-api:1.0-SNAPSHOT
#    ports:
#    - "8081:8080"
#    environment:
#      <<: *database-variables
#    mem_limit: 512m

volumes:
  crudLoja_api: